<script lang="ts">
  import type { PageData } from './$types';
  import { Product } from '$lib/stores/product';
  import ProductCard from '$lib/components/ProductCard.svelte';
  import EditProductCard from '$lib/components/EditProductCard.svelte';
  import { updateProduct, createProduct, deleteProduct } from '$lib/services/products';
  
  export let data: PageData;
  
  // State management - convert plain objects to Product instances
  let products: Product[] = data.products.map((p: any) => new Product(p));
  let editingIndex: number | null = null; // Track which product is being edited
  let isCreating = false; // Track if we're creating a new product
  
  function handleEdit(index: number) {
    editingIndex = index;
    isCreating = false;
  }
  
  async function handleSave(index: number, updatedProduct: Product) {
    try {
      // Convert Product to database format
      const productData = {
        id: updatedProduct.id,
        name: updatedProduct.name,
        description: updatedProduct.description,
        image_path: updatedProduct.imagePath,
        featured: updatedProduct.featured,
        price_cents: updatedProduct.priceCents,
        is_active: updatedProduct.isActive
      };
      
      if (isCreating) {
        // Remove id for new products - Supabase will auto-generate
        const { id, ...newProductData } = productData;
        const result = await createProduct(newProductData);
        if (result && result[0]) {
          // Add the new product to our list with the generated ID
          const newProduct = new Product(result[0]);
          // Remove the placeholder and add the real product
          products = products.slice(0, -1);
          products = [...products, newProduct];
        }
      } else {
        // Update existing product
        await updateProduct(productData);
        products[index] = updatedProduct;
        // Force reactivity update
        products = [...products];
      }
      
      editingIndex = null;
      isCreating = false;
    } catch (error) {
      console.error('Error saving product:', error);
      alert('Failed to save product. Please try again.');
    }
  }
  
  function handleCancel() {
    if (isCreating) {
      // Remove the placeholder product we added for creation
      products = products.slice(0, -1);
    }
    editingIndex = null;
    isCreating = false;
  }
  
  function handleCreate() {
    // Create a placeholder product for editing
    const newProduct = new Product({
      id: '', // Will be generated by database
      name: 'New Product',
      description: 'Product description',
      image_path: '',
      featured: false,
      price_cents: 1200, // Default $12.00
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    });
    
    products = [...products, newProduct];
    editingIndex = products.length - 1;
    isCreating = true;
  }
  
  async function handleDelete(index: number) {
    const product = products[index];
    if (confirm(`Are you sure you want to delete "${product.name}"?`)) {
      try {
        await deleteProduct(product.id);
        products = products.filter((_, i) => i !== index);
        if (editingIndex === index) {
          editingIndex = null;
          isCreating = false;
        }
      } catch (error) {
        console.error('Error deleting product:', error);
        alert('Failed to delete product. Please try again.');
      }
    }
  }
</script>

<div class="max-w-7xl mx-auto px-4 lg:px-8 py-8">
  <!-- Page Header -->
  <div class="mb-8 flex justify-between items-center">
    <div>
      <h1 class="text-3xl font-bold text-black mb-2">Product Management</h1>
      <p class="text-black">Manage your product offerings and visibility</p>
    </div>
    <button 
      on:click={handleCreate}
      class="bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors duration-200"
    >
      + Add New Product
    </button>
  </div>

  <!-- Products Grid -->
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    {#each products as product, index}
      {#if editingIndex === index}
        <EditProductCard 
          product={product} 
          onSave={(updatedFlavor) => handleSave(index, updatedFlavor)}
          onCancel={handleCancel}
        />
      {:else}
        <ProductCard 
          product={product} 
          onEdit={() => handleEdit(index)}
          onDelete={() => handleDelete(index)}
          isAdmin={true}
        />
      {/if}
    {/each}
  </div>
</div>